#!/usr/bin/env bash
set -euo pipefail

mkdir -p "$HOME/.instagrab/CDPProfile"

"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" \
    --remote-debugging-port=9222 \
    --user-data-dir="$HOME/.instagrab/CDPProfile"
